#!/bin/sh

cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# cleanCase # This also deleted the polyMesh
cleanTimeDirectories

rm -f *.dat *.foam
rm -rf processor*
